# Generated by Django 5.2.13 on 2026-05-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
